class AiTexts {
  static const String moduleName = 'AI Module';
  static const String generatingJobs = 'Generating jobs with AI...';
  static const String aiSearchPlaceholder = 'Search for jobs with AI...';
  static const String noAiResults = 'No jobs found. Try a different search.';
  static const String aiGenerationError ='Failed to generate jobs. Please try again.';
  static const String aiPoweredBy = 'Powered by AI';
  static const String aiConfidenceScore = 'AI Confidence Score';
  static const String generatedByAi = 'Generated by AI';
  static const String appTitle = 'AI-Powered Job Search';
  static const String retry = 'Retry';
  static const String refreshAiJobs = 'Refresh AI Jobs';
  static const String generate = 'Generate';
  static const String aiSearchExamples ='Try searching for "Flutter Developer" or "Data Scientist"';
  static const String labelLocation = 'Location';
  static const String allLocations = 'All Locations';
  static const String labelWorkMode = 'Work Mode';
  static const String allModes = 'All Modes';
  static const String labelJobType = 'Job Type';
  static const String allTypes = 'All Types';

  static const String companyLabel = 'Company:';
  static const String locationLabel = 'Location:';
  static const String workModeLabel = 'Work Mode:';
  static const String jobTypeLabel = 'Job Type:';
  static const String salaryLabel = 'Salary:';
  static const String descriptionLabel = 'Description:';
  static const String requirementsLabel = 'Requirements:';
  static const String benefitsLabel = 'Benefits:';
  static const String skillsLabel = 'Skills:';
  static const String close = 'Close';
  static const String viewDetails = 'View Details';
  static const String applyNow = 'Apply Now';
  static const String confidenceLabel = 'Confidence';

  static const String salaryNotSpecified = 'Salary not specified';
  static const String salaryUpTo = 'Up to';
  static const String salaryFrom = 'From';

  static const String requirementsNotSpecified = 'Requirements not specified';
  static const String benefitsNotSpecified = 'Benefits not specified';

  static const String promptRequirementsHeader = 'Requirements';

  static String workModeDisplay(String workMode) {
    switch (workMode) {
      case 'remote':
        return 'Remote';
      case 'hybrid':
        return 'Hybrid';
      case 'onsite':
        return 'On-site';
      default:
        return workMode;
    }
  }

  static String jobTypeDisplay(String jobType) {
    switch (jobType) {
      case 'full_time':
        return 'Full-time';
      case 'part_time':
        return 'Part-time';
      case 'contract':
        return 'Contract';
      case 'internship':
        return 'Internship';
      default:
        return jobType;
    }
  }

  static String formatSalaryRange(int? min, int? max, String? currency) {
    final symbol = _symbolFor(currency);
    if (min == null && max == null) return salaryNotSpecified;
    if (min == null) return '$salaryUpTo $symbol$max';
    if (max == null) return '$salaryFrom $symbol$min';
    return '$symbol$min - $symbol$max';
  }

  static String _symbolFor(String? currency) {
    switch (currency) {
      case 'EUR':
        return '€';
      case 'GBP':
        return '£';
      case 'MXN':
        return '4';
      case 'USD':
      default:
        return '4';
    }
  }

  static String _currencySymbol(String? currency) {
    switch (currency) {
      case 'USD':
        return '4';
      case 'EUR':
        return '€';
      case 'GBP':
        return '£';
      case 'MXN':
        return '4';
      default:
        return '4';
    }
  }
}
