class AiTexts {
  static const String moduleName = 'AI Module';
  static const String generatingJobs = 'Generating jobs with AI...';
  static const String aiSearchPlaceholder = 'Search for jobs with AI...';
  static const String noAiResults = 'No jobs found. Try a different search.';
  static const String aiGenerationError = 'Failed to generate jobs. Please try again.';
  static const String aiPoweredBy = 'Powered by AI';
  static const String aiConfidenceScore = 'AI Confidence Score';
  static const String generatedByAi = 'Generated by AI';
}